# Generated by Django 4.1.1 on 2022-12-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0005_alter_driver_status'),
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uber.location'),
        ),
    ]
