# Generated by Django 4.1.1 on 2022-12-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_alter_passenger_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='locations',
        ),
        migrations.AddField(
            model_name='passenger',
            name='dropoff_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='pickup_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
