# Generated by Django 4.1.1 on 2022-12-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0005_rename_contact_info_passenger_passenger_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='pickup_location',
        ),
    ]
