# Generated by Django 4.1.1 on 2022-12-20 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uber', '0016_alter_driver_car_brand_alter_driver_number_plate_and_more'),
        ('passenger', '0006_remove_passenger_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uber.driver'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='dropoff_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_accepted',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Started'), (3, 'In_Progress'), (4, 'Completed'), (5, 'Accepted'), (6, 'cancel')], default=1),
        ),
        migrations.AddField(
            model_name='passenger',
            name='pickup_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DriverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
