# Generated by Django 4.1.1 on 2022-12-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0008_alter_passenger_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorder',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger'),
        ),
    ]
