# Generated by Django 4.1.1 on 2022-12-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_on',
        ),
    ]
