# Generated by Django 4.1.1 on 2022-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0003_driver_created_on_driver_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
