# Generated by Django 4.1.1 on 2022-12-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0004_alter_driver_created_on_alter_driver_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requested'), (2, 'Started'), (3, 'In_Progress'), (4, 'Completed')], default=1),
        ),
    ]
