# Generated by Django 4.1.1 on 2022-12-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0014_alter_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='car_brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='number_plate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='seat_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='bio',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
