# Generated by Django 4.1.1 on 2022-12-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0015_remove_driver_passenger_remove_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='seat_number',
            field=models.CharField(max_length=20),
        ),
    ]
